/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarburantRouteImport } from './routes/carburant'
import { Route as ReglagesRouteImport } from './routes/reglages'
import { Route as RSlugRouteImport } from './routes/r.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarburantRoute = CarburantRouteImport.update({
  id: '/carburant',
  path: '/carburant',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglagesRoute = ReglagesRouteImport.update({
  id: '/reglages',
  path: '/reglages',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carburant': typeof CarburantRoute
  '/reglages': typeof ReglagesRoute
  '/r/$slug': typeof RSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carburant': typeof CarburantRoute
  '/reglages': typeof ReglagesRoute
  '/r/$slug': typeof RSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carburant': typeof CarburantRoute
  '/reglages': typeof ReglagesRoute
  '/r/$slug': typeof RSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/carburant' | '/reglages' | '/r/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/carburant' | '/reglages' | '/r/$slug'
  id: '__root__' | '/' | '/carburant' | '/reglages' | '/r/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarburantRoute: typeof CarburantRoute
  ReglagesRoute: typeof ReglagesRoute
  RSlugRoute: typeof RSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carburant': {
      id: '/carburant'
      path: '/carburant'
      fullPath: '/carburant'
      preLoaderRoute: typeof CarburantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reglages': {
      id: '/reglages'
      path: '/reglages'
      fullPath: '/reglages'
      preLoaderRoute: typeof ReglagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarburantRoute: CarburantRoute,
  ReglagesRoute: ReglagesRoute,
  RSlugRoute: RSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
